[zh-CN]
  title = "rayrain's blog"
  languageName = "中文"
  weight = 1
  contentdir = "content/zh-CN"

[en]
  title = "rayrain's blog"
  languageName = "English"
  weight = 2
  contentdir = "content/en"
