[TagsCloud]
  Enable = true
  Limit = 10

[Share]
  Enable = false
  AddthisId = "Your AddthisId"

[Comment]
  Enable = true
  Module = "Utterances"
 # LiveReId = "Your LiveReId"
 # WalineSerURL = "Your WalineSerURL"

  # If Module is "Utterances",see https://utteranc.es/
  UtterancesRepo = "Reisen1969/Reisen1969.github.io"
  UtterancesTheme = "github-light"
  UtterancesTitle = "pathname"

#[LeanCloud]
 # AppId = "Your LCAppId"
 # AppKey = "Your LCAppKey"
 # ServerURL = "Your LCServer"

[Statis]
  BusuanziCounter = false
#  CNNZSiteId = "Your CNNZSiteId"
#  BaiduSiteId = "61fc6302f827c41a8f9bec45516aba25"
#  GoogleSiteId = "Your GoogleSiteId"

[OnlineIM]
  Enable = false
#  DaoVoiceId = "Your DaoVoiceId"

[Others]
#  RevolverMapId = "Your RevolverMapId"